# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('english_name', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_home_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Arabic_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('item_arabic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('the_ingredients', models.TextField(blank=True)),
                ('refuse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('enerygy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ASH', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Carbohydrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('potasium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phorphorus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('magnisum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iron', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('zinc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coper', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vitamen_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vitamen_c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thiamen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('riboflabn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.FoodGroup')),
            ],
        ),
        migrations.CreateModel(
            name='HomeStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_arabic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('english_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('home_standrd', models.CharField(blank=True, max_length=200, null=True)),
                ('home_standrd_wieght', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=1000, null=True)),
                ('standard_unit_count', models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True)),
                ('avaliable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refuse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('enerygy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ASH', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Carbohydrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('potasium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phorphorus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('magnisum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iron', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('zinc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coper', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vitamen_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vitamen_c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thiamen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('riboflabn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.FoodTable')),
                ('item_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.ItemGroup')),
                ('meals', models.ManyToManyField(to='foodconf.Meals')),
                ('standard_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.Choises')),
            ],
        ),
    ]
