# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-28 20:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodconf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email_adress', models.EmailField(max_length=250)),
                ('image', models.ImageField(upload_to=b'media')),
                ('password', models.CharField(max_length=200, null=True)),
                ('adress_one', models.CharField(max_length=300, null=True)),
                ('adress_tow', models.CharField(max_length=300, null=True)),
                ('birthday', models.DateField()),
                ('strat_date', models.DateField(default=datetime.datetime(2020, 10, 28, 20, 11, 0, 646211))),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('home_standrd', models.CharField(blank=True, max_length=200, null=True)),
                ('home_standrd_wieght', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('standard_unit_count', models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True)),
                ('refuse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('enerygy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ASH', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Carbohydrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('potasium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phorphorus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('magnisum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iron', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('zinc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coper', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vitamen_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vitamen_c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thiamen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('riboflabn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MsureUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True)),
                ('wieght', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.FoodTable')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='foodmix',
            name='ingredients',
            field=models.ManyToManyField(to='doctors.MsureUnit'),
        ),
        migrations.AddField(
            model_name='foodmix',
            name='item_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.ItemGroup'),
        ),
        migrations.AddField(
            model_name='foodmix',
            name='standard_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.Choises'),
        ),
    ]
