# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-14 12:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hiegth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('email_adress', models.EmailField(blank=True, max_length=250, null=True)),
                ('adress_one', models.CharField(blank=True, max_length=300, null=True)),
                ('strat_date', models.DateField(blank=True, null=True)),
                ('activity', models.CharField(blank=True, choices=[('sedentary', 'sedentary'), ('low_activity', 'low_activity'), ('active', 'active'), ('very_active', 'very_active')], max_length=200, null=True)),
                ('calu', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='strat_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 14, 12, 1, 3, 193320)),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.DoctorProfile'),
        ),
    ]
