# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-14 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20201114_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='strat_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 14, 12, 11, 54, 468300)),
        ),
    ]
