# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-14 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodconf', '0001_initial'),
        ('doctors', '0003_auto_20201114_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealsTFR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodconf.Unit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Patient')),
            ],
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='strat_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 14, 12, 18, 49, 426529)),
        ),
    ]
