# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-14 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20201114_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTFR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_for', models.DateField(blank=True, null=True)),
                ('meals', models.ManyToManyField(to='doctors.MealsTFR')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Patient')),
            ],
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='strat_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 14, 12, 18, 59, 956670)),
        ),
    ]
