# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-14 12:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_auto_20201114_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='strat_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 14, 12, 42, 22, 333945)),
        ),
        migrations.AlterField(
            model_name='patienttfr',
            name='meals',
            field=models.ManyToManyField(blank=True, null=True, to='doctors.MealsTFR'),
        ),
    ]
